# -*- coding: utf-8 -*-
"""Investor Type Breakdown - Final Version

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MwiJGKi9VjoUFzR7fLKjkSb2nqsSV5L_
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf

st.set_page_config(page_title="Investor Dashboard", layout="wide")

st.title("📊 Investor Composition Dashboard")
st.caption("Analyze investor structure across Indonesian equities")

# =========================================
# 📥 LOAD DATA
# =========================================
spreadsheet_id = "1XH1vV9n1snmmeD9qQxmz8BhBywqVfox9eOxqLOqk_dI"
gid = "999061446"

url = f"https://docs.google.com/spreadsheets/d/{spreadsheet_id}/export?format=csv&gid={gid}"

@st.cache_data
def load_data():
    df = pd.read_csv(url)

    df.columns = df.columns.str.strip()

    df['TOTAL SCRIPLESS'] = (
        df['TOTAL SCRIPLESS']
        .astype(str)
        .str.replace('.', '', regex=False)
        .str.replace(',', '', regex=False)
    )
    df['TOTAL SCRIPLESS'] = pd.to_numeric(df['TOTAL SCRIPLESS'], errors='coerce')

    for col in df.columns[3:]:
        if col != 'TOTAL SCRIPLESS':
            df[col] = (
                df[col]
                .astype(str)
                .str.replace('.', '', regex=False)
                .str.replace(',', '', regex=False)
            )
            df[col] = pd.to_numeric(df[col], errors='coerce')

    return df

# =========================================
# 💰 GET PRICE
# =========================================
@st.cache_data(ttl=300)
def get_price(stock):
    try:
        ticker = yf.Ticker(f"{stock.upper()}.JK")
        data = ticker.history(period="1d")
        return float(data['Close'].iloc[-1])
    except:
        return None

df = load_data()

# =========================================
# 🎛️ MODE
# =========================================
mode = st.sidebar.radio(
    "Select Mode",
    ["Investor Breakdown", "Ranking Tool"]
)

# =========================================
# 📊 MODE 1: INVESTOR BREAKDOWN
# =========================================
if mode == "Investor Breakdown":

    stock = st.text_input("Enter Stock Code", "BBCA")
    sort = st.radio("Sort Order", ["Descending", "Ascending"])

    if stock:

        temp = df[df['SHARE CODE'] == stock.upper()]

        if temp.empty:
            st.error("❌ Stock not found")
        else:
            row = temp.iloc[0]
            total_scripless = row['TOTAL SCRIPLESS']

            investor_cols = [col for col in df.columns[3:] if col != 'TOTAL SCRIPLESS']
            investor_data = row[investor_cols]

            investor_df = investor_data.reset_index()
            investor_df.columns = ['Investor Type', 'Shares']

            investor_df = investor_df.dropna()
            investor_df = investor_df[investor_df['Shares'] > 0]

            if pd.isna(total_scripless) or total_scripless <= 0:
                total_scripless = investor_df['Shares'].sum()

            # %
            investor_df['%'] = (investor_df['Shares'] / total_scripless) * 100

            # price & value
            price = get_price(stock)

            if price:
                investor_df['Value (IDR)'] = investor_df['Shares'] * price
                st.success(f"Price: Rp {price:,.0f}")
            else:
                st.warning("⚠️ Price not available")

            # sort
            investor_df = investor_df.sort_values(
                by='Shares',
                ascending=(sort == 'Ascending')
            ).reset_index(drop=True)

            st.subheader(f"📌 Investor Breakdown: {stock.upper()}")

            col1, col2 = st.columns(2)

            # TABLE
            with col1:
                st.dataframe(
                    investor_df,
                    use_container_width=True,
                    column_config={
                        "Shares": st.column_config.NumberColumn(format="%,.0f"),
                        "%": st.column_config.NumberColumn(format="%.2f"),
                        "Value (IDR)": st.column_config.NumberColumn(format="%,.0f")
                    }
                )

            # CHART
            with col2:
                chart_df = investor_df.sort_values(by='%', ascending=False).head(10)[::-1]

                fig, ax = plt.subplots()
                ax.barh(chart_df['Investor Type'], chart_df['%'])

                for i, v in enumerate(chart_df['%']):
                    ax.text(v + 0.5, i, f"{v:.1f}%", va='center')

                ax.set_title("Top 10 Investor Composition")
                st.pyplot(fig)

                coverage = chart_df['%'].sum()
                st.caption(f"Top 10 represents {coverage:.2f}% of total ownership")

# =========================================
# 🏆 MODE 2: RANKING TOOL
# =========================================
else:

    st.subheader("🏆 Ranking Tool")

    column = st.selectbox("Select Investor Type", df.columns[3:])
    keyword = st.text_input("Search Stock (optional)", "")
    top_n = st.slider("Top N", 5, 50, 10)

    # 🔥 TOGGLE
    rank_by = st.radio("Rank By", ["Value (IDR)", "% Ownership"])

    temp = df.copy()

    if keyword:
        temp = temp[temp['SHARE CODE'].str.contains(keyword.upper(), na=False)]

    temp = temp.dropna(subset=[column])
    temp = temp[temp[column] > 0]

    # shares
    temp['Shares'] = temp[column]

    # %
    temp['%'] = (temp['Shares'] / temp['TOTAL SCRIPLESS']) * 100

    # price
    prices = {s: get_price(s) for s in temp['SHARE CODE']}
    temp['Price'] = temp['SHARE CODE'].map(prices)

    # value
    temp['Value (IDR)'] = temp['Shares'] * temp['Price']

    # 🔥 SORT DYNAMIC
    if rank_by == "Value (IDR)":
        temp = temp.sort_values(by='Value (IDR)', ascending=False)
    else:
        temp = temp.sort_values(by='%', ascending=False)

    temp = temp[['SHARE CODE', 'ISSUER NAME', 'Shares', '%', 'Price', 'Value (IDR)']].head(top_n)

    temp = temp.reset_index(drop=True)

    st.dataframe(
        temp,
        use_container_width=True,
        column_config={
            "Shares": st.column_config.NumberColumn(format="%,.0f"),
            "Price": st.column_config.NumberColumn(format="%,.0f"),
            "Value (IDR)": st.column_config.NumberColumn(format="%,.0f"),
            "%": st.column_config.NumberColumn(format="%.2f")
        }
    )